all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B193315/Hello
	java -classpath "../.." s4.B193315/Frequencer
#	java -classpath "../.." s4.B193315/InformationEstimator
#	java -classpath "../.." s4.B193315/TestCase
